/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.shimonp21.mynamespace;

import org.junit.jupiter.api.Test;

import io.github.shimonp21.mynamespace.ShimonLibTest;

import static org.junit.jupiter.api.Assertions.*;

class ShimonLibTest {
    @Test void someLibraryMethodReturnsTrue() {
        ShimonLib obj = new ShimonLib();
        assertEquals(obj.myAdd(1, 5), 6);
    }
}
