name: Release dagster-pipes-typescript

on:
  push:
    tags:
      - 'release-*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./gpkg/

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test

      - name: Integration Test
        run: echo "ok"

      - name: Publish and Release
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
