name: Release dagster-pipes-typescript

on:
  push:
    tags:
      - 'release-*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./gpkg/

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dagster-io'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}